name: tproject
description: "Template for project"
publish_to: 'none'
environment:
  sdk: ^3.5.2


# --------------- PACKAGES --------------- #

dependencies:
  flutter:
    sdk: flutter

  # Http
  dio: ^5.7.0

  # State management
  get: ^4.6.6

  # Local storage
  get_storage: ^2.1.1

  # Svg
  flutter_svg: ^2.0.11

  # Formatting data
  intl: ^0.19.0

  # Permissions
  permission_handler: ^11.3.1

  # Logging code
  logger: ^2.4.0

  # Web links
  url_launcher: ^6.3.1

  # Loading effect
  shimmer: ^3.0.0

  # Dynamic height elements in grid
  flutter_staggered_grid_view: ^0.7.0

  # Images caching
  cached_network_image: ^3.4.1

  # Firebase, notifications, auth
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_auth: ^5.3.1

  # Localization
  flutter_localizations:
    sdk: flutter

  # Parse html
  html: ^0.15.5

  # Share content
  share_plus: ^10.1.1

  # App info
  package_info_plus: ^8.1.0

  # Device info
  device_info_plus: ^11.1.0

  # Mask for input
  easy_mask: ^2.0.1

  # Pick image
  image_picker: ^1.1.2

  # Bottom navigation menu
  persistent_bottom_nav_bar_v2: ^5.3.1

  # Network connection
  connectivity_plus: ^6.1.0

  # FTP
  pin_code_fields: ^8.0.1


# --------------- DEV PACKAGES --------------- #

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


# --------------- SETTINGS --------------- #

# Flutter
flutter:
  generate: true
  uses-material-design: true

  # --------------- ASSETS --------------- #

  assets:
    - assets/
    - assets/img/
    - assets/icons/

  # --------------- FONTS --------------- #

  fonts:
    # Base font
    - family: Circe
      fonts:
        - asset: assets/fonts/Circe-Light.ttf
          weight: 300
        - asset: assets/fonts/Circe-Regular.ttf
          weight: 400
        - asset: assets/fonts/Circe-Bold.ttf
          weight: 700

    # Icons fontAwesome
    - family: FontAwesomeLight
      fonts:
        - asset: assets/fonts/FontAwesome-Light.ttf
          weight: 300
    - family: FontAwesomeRegular
      fonts:
        - asset: assets/fonts/FontAwesome-Regular.ttf
          weight: 400
    - family: FontAwesomeBold
      fonts:
        - asset: assets/fonts/FontAwesome-Bold.ttf
          weight: 700