/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String CIRCE_BOLD = 'Circe-Bold';
  static const String CIRCE_LIGHT = 'Circe-Light';
  static const String CIRCE_REGULAR = 'Circe-Regular';
  static const String FONTAWESOME_BOLD = 'FontAwesome-Bold';
  static const String FONTAWESOME_LIGHT = 'FontAwesome-Light';
  static const String FONTAWESOME_REGULAR = 'FontAwesome-Regular';
}
